### ISSUE TITLE
[BUG] failed to initialize

### ISSUE THREAD

**Issue by baixiaoyu2997** [0x3at/synceverything#4]
### Info
mac 15.5

cursor v1.1.3

### Logs
[INFO] 2025-06-20T01:54:04.058Z: Extension activation started
[INFO] 2025-06-20T01:54:04.059Z: Starting extension initialization...
[INFO] 2025-06-20T01:54:04.092Z: Found settings.json at: /Users/l.rain/Library/Application Support/Cursor/User/settings.json
[INFO] 2025-06-20T01:54:04.103Z: Found keybindings.json at: /Users/l.rain/Library/Application Support/Cursor/User/keybindings.json
[INFO] 2025-06-20T01:54:04.104Z: Initializing master gist...
[INFO] 2025-06-20T01:54:29.963Z: Creating new master gist...
[ERROR] 2025-06-20T01:54:29.964Z: Failed to read settings file: undefined
Details: {
  "code": "ERR_INVALID_ARG_TYPE"
}
[ERROR] 2025-06-20T01:54:29.965Z: Failed to initialize extension
Details: {
  "code": "ERR_INVALID_ARG_TYPE"
}
[INFO] 2025-06-20T01:54:35.577Z: Starting extension initialization...
[INFO] 2025-06-20T01:54:35.587Z: Found settings.json at: /Users/l.rain/Library/Application Support/Cursor/User/settings.json
[INFO] 2025-06-20T01:54:35.588Z: Found keybindings.json at: /Users/l.rain/Library/Application Support/Cursor/User/keybindings.json
[INFO] 2025-06-20T01:54:35.588Z: Initializing master gist...
[INFO] 2025-06-20T01:54:36.856Z: Creating new master gist...
[ERROR] 2025-06-20T01:54:36.856Z: Failed to read settings file: undefined
Details: {
  "code": "ERR_INVALID_ARG_TYPE"
}
[ERROR] 2025-06-20T01:54:36.857Z: Failed to initialize extension
Details: {
  "code": "ERR_INVALID_ARG_TYPE"
}
[ERROR] 2025-06-20T01:54:50.537Z: Extension failed to initialize properly

**Comment by 0x3at** [comment]
Working on a refactor which should resolve this - will provide updates shortly. 

In the meantime, what happens when you manually set the settings path? 

Does the same thing occur?

**Comment by TheWirv** [comment]
However, if I try to create a new sync profile (this is the way to sync other than the default profiles' settings, right?), I still get the error:

![Image](https://github.com/user-attachments/assets/ef0c9107-f953-4520-9f1e-45b656048a69)

**Comment by laris** [comment]
here is the patch 
```
diff --git a/src/core/profile.ts b/src/core/profile.ts
index 2811e95..2c676ac 100644
--- a/src/core/profile.ts
+++ b/src/core/profile.ts
@@ -105,7 +105,11 @@ export const validatePaths = async (
                if (!path) {
                        path = await findConfigFile(appName, 'settings.json');
                }
-               if (!path) {
+               if (path) {
+                       // Store the found path in the context store
+                       settingsPath.set(path);
+                       logger.info(`Stored settings path: ${path}`);
+               } else {
                        await setManualPath(settingsPath, 'settings');
                }
        }
@@ -117,7 +121,11 @@ export const validatePaths = async (
                        path = await findConfigFile(appName, 'keybindings.json');
                }
 
-               if (!path) {
+               if (path) {
+                       // Store the found path in the context store
+                       keybindingsPath.set(path);
+                       logger.info(`Stored keybindings path: ${path}`);
+               } else {
                        await setManualPath(keybindingsPath, 'keybindings');
                }
        }
```

**Comment by strazto** [comment]
I seem to get this on `0.2.0`
